####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from router import Router
import json
from packet import Packet
import heapq


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.neighbors = {}      # port -> (endpoint, cost)
        self.endpoint_port = {}  # endpoint -> port

        self.seq_num = 0

        self.lsdb = {
            self.addr: {
                "seq": 0,
                "links": {}
            }
        }
        self.forwarding_table = {}

    def broadcast_lsp(self):
        data = {
            "router": self.addr,
            "seq": self.seq_num,
            "links": self.lsdb[self.addr]["links"]
        }

        pkt = Packet(
            Packet.ROUTING,
            self.addr,
            self.addr,
            json.dumps(data)
        )

        for port in self.neighbors:
            self.send(port, pkt)

    def update_forwarding_table(self):
        graph = {}

        for router, info in self.lsdb.items():
            graph.setdefault(router, {})

            for nbr, cost in info["links"].items():
                graph.setdefault(nbr, {})
                graph[router][nbr] = cost
                graph[nbr][router] = cost

        dist = {self.addr: 0}
        prev = {}

        pq = [(0, self.addr)]

        while pq:
            d, u = heapq.heappop(pq)

            if d > dist[u]:
                continue

            for v, w in graph.get(u, {}).items():
                nd = d + w

                if v not in dist or nd < dist[v]:
                    dist[v] = nd
                    prev[v] = u
                    heapq.heappush(pq, (nd, v))

        self.forwarding_table = {}

        for dest in dist:
            if dest == self.addr:
                continue

            node = dest

            while prev.get(node) != self.addr:
                if node not in prev:
                    break
                node = prev[node]

            if node in self.endpoint_port:
                self.forwarding_table[dest] = self.endpoint_port[node]

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table:
                self.send(
                    self.forwarding_table[packet.dst_addr],
                    packet
                )
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            data = json.loads(packet.content)

            router = data["router"]
            seq = data["seq"]
            links = data["links"]

            if (
                router not in self.lsdb
                or seq > self.lsdb[router]["seq"]
            ):

                self.lsdb[router] = {
                    "seq": seq,
                    "links": links
                }

                self.update_forwarding_table()

                for p in self.neighbors:
                    if p != port:
                        self.send(p, packet)

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        self.neighbors[port] = (endpoint, cost)
        self.endpoint_port[endpoint] = port

        self.lsdb[self.addr]["links"][endpoint] = cost

        self.seq_num += 1
        self.lsdb[self.addr]["seq"] = self.seq_num

        self.update_forwarding_table()
        self.broadcast_lsp()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        endpoint = self.neighbors[port][0]

        del self.neighbors[port]
        del self.endpoint_port[endpoint]

        if endpoint in self.lsdb[self.addr]["links"]:
            del self.lsdb[self.addr]["links"][endpoint]

        self.seq_num += 1
        self.lsdb[self.addr]["seq"] = self.seq_num

        self.update_forwarding_table()
        self.broadcast_lsp()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            self.seq_num += 1
            self.lsdb[self.addr]["seq"] = self.seq_num

            self.broadcast_lsp()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
